# Generated by Django 4.2.6 on 2023-10-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/%Y/%m'),
        ),
        migrations.AddField(
            model_name='student',
            name='StudentEmail',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StudentID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
